#
# Copyright (c) 2021 Red Hat, Inc.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#   http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#

builds:
- env:
  - CGO_ENABLED=0
  mod_timestamp: '{{ .CommitTimestamp }}'
  flags:
  - -trimpath
  goos:
  - darwin
  - linux
  - windows
  goarch:
  - amd64
  - arm64
  binary: '{{ .ProjectName }}_v{{ .Version }}'
  ldflags:
  - -X github.com/terraform-redhat/terraform-provider-rhcs/build.Version={{.Version}}
  - -X github.com/terraform-redhat/terraform-provider-rhcs/build.Commit={{.Commit}}
archives:
- format: zip
  name_template: '{{ .ProjectName }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}'
checksum:
  extra_files:
  - glob: 'terraform-registry-manifest.json'
    name_template: '{{ .ProjectName }}_{{ .Version }}_manifest.json'
  name_template: '{{ .ProjectName }}_{{ .Version }}_SHA256SUMS'
  algorithm: sha256
signs:
- artifacts: checksum
  args:
  - '--batch'
  - '--local-user'
  - '{{ .Env.GPG_FINGERPRINT }}'
  - '--output'
  - '${signature}'
  - '--detach-sign'
  - '${artifact}'
release:
  extra_files:
  - glob: 'terraform-registry-manifest.json'
    name_template: '{{ .ProjectName }}_{{ .Version }}_manifest.json'
  name_template: 'Release {{ .Version }}'
changelog:
  skip: true
